name: Publish

on:
  workflow_dispatch:

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'

    - run: npm ci

    - run: npm run build --if-present

    - run: npm install -g @vscode/vsce

    - name: Publish Release
      shell: pwsh
      env:
        GH_TOKEN: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
        BRANCH_NAME: ${{ github.ref_name }}
        MARKETPLACE_PAT: ${{ secrets.MARKETPLACE_PAT }}
      run: |
        ./tools/publish_release.ps1
